// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Shop4UML.Model
{
    public class ModelInput
    {
        [ColumnName("birth_year"), LoadColumn(0)]
        public float Birth_year { get; set; }


        [ColumnName("user_gender"), LoadColumn(1)]
        public float User_gender { get; set; }


        [ColumnName("product_category"), LoadColumn(2)]
        public float Product_category { get; set; }


    }
}
